language: ruby
env:
  - DB=sqlite

addons:
        chrome: stable
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake db:seed RAILS_ENV=test --trace
  - bundle exec rake cucumber

